#!/bin/bash

# custom AppRun for MidnightSun AppImage

# path of the extracted AppRun
HERE="$(dirname "$(readlink -f "${0}")")"
MIDNIGHTSUN_PATH=/usr/bin/sunshine
MIDNIGHTSUN_BIN_HERE=$HERE/usr/bin/sunshine
MIDNIGHTSUN_SHARE_HERE=$HERE/usr/share/sunshine

# Set APPDIR when running directly from the AppDir:
if [ -z "$APPDIR" ]; then
    ARGV0="AppRun"
fi

cd "$HERE" || exit 1

function help() {
echo "
 ------------------------------
   MidnightSun AppImage package.
 ------------------------------

 midnightsun.AppImage options
 ------------------------

 Usage:  $ARGV0  --help, -h
 ------            # This message

         $ARGV0  --install, -i
                   # Install input rules sunshine.service files. Restart required.

         $ARGV0  --remove, -r
                   # Remove input rules sunshine.service files.

         $ARGV0  --appimage-help
                   # Show available AppImage options

 midnightsun options
 ----------------
"
# print sunshine binary help, replacing the sunshine command in usage statement
"$MIDNIGHTSUN_BIN_HERE" --help | sed -e "s#$MIDNIGHTSUN_BIN_HERE#$ARGV0#g"
}

function install() {
  # user input rules
  # shellcheck disable=SC2002
  cat "$MIDNIGHTSUN_SHARE_HERE/udev/rules.d/60-sunshine.rules" | sudo tee /etc/udev/rules.d/60-sunshine.rules
  cat "$MIDNIGHTSUN_SHARE_HERE/modules-load.d/60-sunshine.conf" | sudo tee /etc/modules-load.d/60-sunshine.conf
  sudo modprobe uhid
  sudo udevadm control --reload-rules
  sudo udevadm trigger --property-match=DEVNAME=/dev/uinput
  sudo udevadm trigger --property-match=DEVNAME=/dev/uhid

  # sunshine service
  mkdir -p ~/.config/systemd/user
  cp -r "$MIDNIGHTSUN_SHARE_HERE/systemd/user/" ~/.config/systemd/
  # patch service executable path
  sed -i -e "s#$MIDNIGHTSUN_PATH#$(readlink -f $ARGV0)#g" ~/.config/systemd/user/app-com.midnightsun.app.service

  # setcap for VKMS access
  sudo setcap cap_sys_admin,cap_sys_nice+p "$(readlink -f "$MIDNIGHTSUN_BIN_HERE")"
}

function remove() {
  # remove input rules
  sudo rm -f /etc/udev/rules.d/60-sunshine.rules

  # remove uhid module loading config
  sudo rm -f /etc/modules-load.d/60-sunshine.conf

  # remove service
  sudo rm -f ~/.config/systemd/user/app-com.midnightsun.app.service
}

# process arguments
if [ "x$1" == "xhelp" ] || [ "x$1" == "x--help" ] || [ "x$1" == "x-h" ] ; then
    help
    exit $?
fi

if [ "x$1" == "xinstall" ] || [ "x$1" == "x--install" ] || [ "x$1" == "x-i" ] ; then
    install
    exit $?
fi

if [ "x$1" == "xremove" ] || [ "x$1" == "x--remove" ] || [ "x$1" == "x-r" ] ; then
    remove
    exit $?
fi

# create config directory if it doesn't exist
mkdir -p ~/.config/sunshine

# run sunshine
"$MIDNIGHTSUN_BIN_HERE" $@
